"""HunterPie Wilds abnormality ID -> human-readable name mapping.

Source: HunterPie/Game/Wilds/Data/AbnormalityData.xml + Localization/en-us.xml
"""
ABNORMALITY_NAMES: dict[str, str] = {
    # Consumables
    "Consumables.10": "Wiggly Litchy",
    "Consumables.14": "Might Seed",
    "Consumables.1C": "Might Pill",
    "Consumables.24": "Demon Ammo",
    "Consumables.30": "Demon Powder",
    "Consumables.38": "Adamant Seed",
    "Consumables.40": "Adamant Pill",
    "Consumables.48": "Armor Ammo",
    "Consumables.54": "Hardshell Powder",
    "Consumables.5C": "Dash Juice",
    "Consumables.64": "Natural Healing",
    "Consumables.6C": "Hot Drink",
    "Consumables.74": "Cool Drink",
    "Consumables.7C": "Demondrug",
    "Consumables.88": "Mega Demondrug",
    "Consumables.94": "Armorskin",
    "Consumables.A0": "Mega Armorskin",
    # Songs
    "Songs.1": "Self-Improvement",
    "Songs.2": "Health Rec.",
    "Songs.3": "Health Rec. (M)",
    "Songs.4": "Health Rec. (L)",
    "Songs.5": "Health Rec. (S) + Antidote",
    "Songs.6": "Health Rec. (L) + Antidote",
    "Songs.7": "Recovery Speed (S)",
    "Songs.8": "Recovery Speed (L)",
    "Songs.9": "Stamina Use Reduced",
    "Songs.10": "Stamina Use Reduced (L)",
    "Songs.11": "Attack Up",
    "Songs.12": "Attack Up (L)",
    "Songs.13": "Elemental Attack Up",
    "Songs.14": "Abnormal Status Atk. Up (S)",
    "Songs.15": "Defense Up",
    "Songs.16": "Defense Up (L)",
    "Songs.17": "Divine Protection",
    "Songs.18": "Fire Res. Up",
    "Songs.19": "Fire Res. Up (L)",
    "Songs.20": "Water Res. Up",
    "Songs.21": "Water Res. Up (L)",
    "Songs.22": "Thunder Res. Up",
    "Songs.23": "Thunder Res. Up (L)",
    "Songs.24": "Ice Res. Up",
    "Songs.25": "Ice Res. Up (L)",
    "Songs.26": "Dragon Res. Up",
    "Songs.27": "Dragon Res. Up (L)",
    "Songs.28": "Earplugs (S)",
    "Songs.29": "Earplugs (L)",
    "Songs.30": "Tremors Negated",
    "Songs.31": "Paralysis Negated",
    "Songs.32": "Stun Negated",
    "Songs.33": "Wind Pressure Negated",
    "Songs.34": "All Wind Pressure Negated",
    "Songs.36": "Env. Damage Negated",
    "Songs.37": "Knockback Negated",
    "Songs.38": "All Ailments Negated",
    "Songs.39": "Blights Negated",
    "Songs.42": "Attack and Def. Up",
    "Songs.43": "Affinity Up",
    "Songs.44": "Tool Use Drain Red.",
    "Songs.45": "Tool Use Drain Red. (L)",
    "Songs.46": "Sonic Barrier",
    "Songs.53": "Echo Bubble: Evasion & Move Speed",
    "Songs.54": "Echo Bubble: Health Regen",
    "Songs.55": "Echo Bubble: Stamina Regen",
    "Songs.56": "Echo Bubble: Attack & Affinity",
    "Songs.57": "Echo Bubble: Def & Ele Res",
    "Songs.58": "Echo Bubble: Ailments Negated",
    # Debuffs
    "Debuffs.0": "Poison",
    "Debuffs.1": "Stench",
    "Debuffs.2": "Blastblight",
    "Debuffs.3": "Bleed",
    "Debuffs.4": "Defense Down",
    "Debuffs.5": "The Frenzy",
    "Debuffs.6": "Stun",
    "Debuffs.7": "Paralysis",
    "Debuffs.8": "Sleep",
    "Debuffs.9": "Webbed",
    "Debuffs.10": "Frozen",
    "Debuffs.11": "Fireblight",
    "Debuffs.12": "Thunderblight",
    "Debuffs.13": "Waterblight",
    "Debuffs.14": "Iceblight",
    "Debuffs.15": "Dragonblight",
    "Debuffs.16": "Bubbleblight",
    # Palico
    "Palico.1": "Sporenet: Purrtection",
    "Palico.2": "Sporenet: Purrtection (L)",
    "Palico.4": "Sporenet: Power",
    "Palico.5": "Sporenet: Power (L)",
    # Skills
    "Skills.18": "Protective Polish",
    "Skills.29": "Offensive Guard",
    "Skills.30": "Critical Draw",
    "Skills.64": "Latent Power",
    "Skills.67": "Buttery Leathercraft",
    "Skills.111": "Counterstrike",
    "Skills.114": "Coalescence",
    "Skills.115": "Burst",
    "Skills.116": "Adrenaline Rush",
    "Skills.117": "Ambush",
    "Skills.150": "Guardian's Pulse",
    "Skills.152": "Doshaguma's Might",
    "Skills.154": "Uth Duna's Cover",
    "Skills.156": "Jin Dahaad's Revolt",
    "Skills.159": "War Cry",
    "Skills.164": "Elemental Absorption",
    "Skills.165": "Convert Element",
    "Skills.168": "Xu Wu's Vigor",
    "Skills.184": "Guardian's Protection",
    "Skills.213": "Leviathan's Fury",
    "Skills.230": "Power Stone",
    "Skills.234": "Darkside",
}


def get_abnormality_name(abnormality_id: str) -> str:
    """Resolve 'Consumables_Consumables.30' -> 'Demon Powder'."""
    if "_" in abnormality_id:
        short = abnormality_id.split("_", 1)[1]
    else:
        short = abnormality_id
    return ABNORMALITY_NAMES.get(short, abnormality_id)
